export const DATABASE_PROVIDER = 'DATABASE_CONNECTION';

export const USER_MODEL_PROVIDER = 'USER_MODEL';
export const SETTLEMENT_MODEL_PROVIDER = 'SETTLEMENT_MODEL';
export const SETTLEMENT_SAVING_MODEL_PROVIDER = 'SETTLEMENT_SAVING_MODEL';
